spring:
  application:
    name: GenAi
  profiles:
    active: dev
  ai:
    google:
      genai:
        api-key: XXXXXXXXXXXXXXXXXXX
        chat:
          model: gemini-3.5-flash-lite
    openai:
      api-key: XXXXXXXXXXX
      chat:
        model: gpt-4o-mini