spring:
  application:
    name: AiAgent
  ai:
    google:
      genai:
        api-key: XXXXXXXXXXXXXXXXXXX
        chat:
          model: gemini-3.5-flash-lite
  profiles:
    active: dev
server:
  port: 8081
